use abc;
drop table student;
create table student(sno int,sname varchar(40) NOT NULL,course varchar(40),marks int,fees int); 
desc student;
insert into student values(101,'Steven','PGDAC',800,70000);
select * from student;
update student set sname=NULL where sno=100;
alter table student add constraint s_uk unique(sno);
insert into student values(102,'Beitz','PGDAC',500,75000);
alter table student add constraint s_pk primary key(sno);
insert into student values(103,'Beitz','PGDITISS',600,80000);
update student set sno=NULL where sname='Steven';
create table mar(marks int primary key);
insert into mar values(500),(600),(800);
insert into mar values(700),(900);
select * from mar;
alter table student add constraint s_fk foreign key(marks) references mar(marks);
insert into student values(104,'sdert','PGDGI',600,75000);
update student set marks=900 where sno=104;
delete from mar where marks=800;
use information_schema;
show tables;
desc key_column_usage;
select * from key_column_usage where table_name='STUDENT'; 
use abc;
insert into student values(106,'bghjyt','PGDGI',NULL,76000);
alter table student modify course varchar(40) DEFAULT 'PGDAC';
insert into student values(107,'bghjyt',default,800,76000);